### ISSUE TITLE
La gestion des retours en erreur

### ISSUE THREAD

**Issue by richard-olvera** [before-interop/E-intervention-V2.0#1]
Pour moi on ne doit pas retourner du http 200 OK si le formats de la requete n'est pas celui attendu

on doit utiliser les code http d'erreur 400 Bad Request pour CHAMPS_NON_RENSEIGNE ou MAUVAIS_FORMAT 
pour CODE_OI_INCONNU => 403
pour PM_INCONNU  => 404

Et ca pour toutes les reponses HTTP

![image](https://github.com/user-attachments/assets/6e1d90c3-cc18-4b99-a603-e56ad2fad80d)

**Comment by Fat-slitane** [comment]
ils seront ajouté dans la nouvelle version
