### ISSUE TITLE
Erreur "Operations must have unique operationIds."

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/E-intervention-V2.0#5]
INTERVENTION-OI/INTERVENTION-OI-consumer-swagger.json

Les routes PUT /interventions-oi/compte-rendu et PUT /interventions-oi ont le même operationId "modifierInterventionOI" alors que cette valeur doit être unique.

idem pour le swagger INTERVENTION-OI/INTERVENTION-OI-provider-swagger.json

idem répétition de la valeur "modifierInterventionOI" dans la liste des tags

**Comment by Fat-slitane** [comment]
En phase, il sera corrigé dans la nouvelle version.

**Comment by alexisthethe** [comment]
D'accord merci.

Idem gardons les issue ouvertes tant que la correction n'est pas mergée.

**Comment by f-teyssier** [comment]
Erreur prise en compte , je cloture
