### ISSUE TITLE
Pourquoi swagger "-provider" et "-consumer" ?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/E-intervention-V2.0#6]
C'est quoi la différence entre les swaggers "-provider" et "-consumer" ?
Quel est l'intérêt ?

Et pourquoi ne pas faire simplement 1 seul swagger comme c'était le cas pour e-intervention V1 ?

**Comment by Fat-slitane** [comment]
la différence entre provider et consumer:
le provider est destiné a celui qui va exposé cette api
le consumer ce lui qui va appeler l'api ou le consommateur.
Si c'est perturbant pour vous je vais supprimer le consumer.

**Comment by alexisthethe** [comment]
Oui SVP vous pouvez fusionner les 4 swaggers pour en avoir qu'un seul comme discuté lors de notre atelier de mardi 26/11

**Comment by f-teyssier** [comment]
Le compromis a été de supprimer les 2 version consumer et provider pour ne garder que provider. Les définitions sont scindées en 2 parties OI et DO comme proposée ici : https://before-interop.github.io/E-Intervention/?urls.primaryName=E-Intervention-DO-v2.0.0
