### ISSUE TITLE
Ne pas modifier e-intervention V1

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/E-intervention-V2.0#7]
Pourquoi avoir modifier le nom des routes /intervention_DO et /intervention_OI validées pour le lot 1 ?
Pourquoi avoir changer tout le contrat d'interface (structure du JSON et nom des champs) de ces 2 routes ???

**Comment by Fat-slitane** [comment]
le lot 2 est diffèrent de lot 1.

**Comment by alexisthethe** [comment]
Toutefois, nous souhaitons garder les mêmes conventions que celles qui ont été introduites initialement dans le lot 1 et éviter de changer la nomenclature entre les 2 version si cela n'est pas nécessaire et indispensable

**Comment by alexisthethe** [comment]
OK pour garder le nommage actuel.
Cela ne met pas en péril l'implémntation
