### ISSUE TITLE
Pourquoi avoir enlevé le champ "refPBO" dans le flux M2 ?

### ISSUE THREAD

**Issue by alexisthethe** [before-interop/E-intervention-V2.0#9]
Dans le lot 1, on renvoyait l'infoirmation de la ref PBO.
Or dans cette version, ce champ a été supprimé. Pourquoi ? Un oubli ?

Par ailleurs, l'information "refPTO" est reçu lors du flux M1, pourquoi ne pas l'envoyer aussi dans le flux M2 ?

**Comment by Fat-slitane** [comment]
c'est une décision métier interop : l'OI doit masquer ces informations aux OC.

**Comment by alexisthethe** [comment]
Non, il a été décidé en atelier de mardi 28/11 de réintégrer ce champ.

**Comment by alexisthethe** [comment]
fait
